CREATE TABLE CLIENTE(
    ID_CLIENTE VARCHAR2(20),
    NOMBRE VARCHAR2(30),
    NºTLF VARCHAR2(12),
    DIRECCION VARCHAR2(30),
    CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PEDIDO(
    ID_PEDIDO VARCHAR2(20),
    PRECIO NUMBER(5,2),
    NºARTICULOS NUMBER(5),
    CONSTRAINT PK_ID_PEDIDO PRIMARY KEY (ID_PEDIDO)
);

CREATE TABLE PRODUCTO(
    ID_PRODUCTO VARCHAR2(20),
    PRECIO_PRODUCTO NUMBER(5,2),
    STOCK NUMBER(5),
    CONSTRAINT PK_ID_PRODUCTO PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE ALMACEN(
    ID_ALMACEN VARCHAR2(20),
    CONSTRAINT PK_ID_ALMACEN PRIMARY KEY (ID_ALMACEN)
);