CREATE TABLE CLIENTE(
    ID_CLIENTE VARCHAR(20),
    NOMBRE VARCHAR(30),
    NUM_TLF VARCHAR(12),
    DIRECCION VARCHAR(30),
    CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PEDIDO(
    ID_PEDIDO VARCHAR(20),
    PRECIO INTEGER(5,2),
    NUM_ARTICULOS INTEGER(5),
    CONSTRAINT PK_ID_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE PRODUCTO(
    ID_PRODUCTO VARCHAR(20),
    PRECIO_PRODUCTO INTEGER(5,2),
    STOCK INTEGER(5),
    CONSTRAINT PK_ID_PRODUCTO PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE ALMACEN(
    ID_ALMACEN VARCHAR(20),
    CONSTRAINT PK_ID_ALMACEN PRIMARY KEY (ID_ALMACEN)
);